spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/magasbook
    username: malik
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # validate / update / create / create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080